package ui;

import java.util.Scanner;

public class Main {

    /*
    For the project class, when Green accepts a project from a client, it must store the project name, client name, planned start date for the project and planned end date for the project, the value corresponding to the project budget and the names and cell phone numbers of both Green’s and client’s project managers.

    For each stage of a project (start, analysis, design, execution, closure and monitoring and control of the project), each stage will have a planned start and end date as well as an actual start and end date. Additionally, approval of compliance with the stage is saved.

    For knowledge capsules generated by collaborators in each stage of a project: A capsule has a unique identifier, a description of the situation to be recorded, a type of capsule (technical, management, domain or experiences), the name and position of the collaborator and learning or lesson learned from that situation.
    */

    private static Scanner scanner = new Scanner(System.in);

    private static void print(Object uwu){
        System.out.println(uwu);
    }

    public static void main(String[] args) {
        print("Insert ur name: ");
        String name = scanner.nextLine();
        print("Your name is: " + name);
    }

}